### ISSUE TITLE
Repo for contribution system provisioning

### ISSUE THREAD

**Issue by Pierozi** [hoaproject/Central#17]
Hello Hoa community,

I've build a little `Vagrantfile` for **_Hoa_**, with php provisioned by `Chef` and box hosted in `Vagrant Atlas` built himself with `Packer`. 
That should be great if we can centralise all community contribution like this in new repository can contain Packer, Vagrant, Chef, Docker...

What do you think ?

BTW, this is also useful to `Hoa/Comte-Intatto` , for run Hoa test with different version and system.

**Comment by Hywan** [comment]
I suggseted `Contributions/Vagrant/` or `Contributions/Packer/` (or `…/Chef/`) on IRC.

**Comment by Pierozi** [comment]
@Hywan you mean a repository named Contributions with directory inside ? Vagrant, Packer, Chef...

**Comment by Hywan** [comment]
@Pierozi Yup, see http://git.hoa-project.net/.

**Comment by jubianchi** [comment]
@Pierozi great!

@Hywan I think naming the repository against a software name or a technology is not a good thing. Let's say tomorrow I want to contribute a `Dockerfile` but the repository is named `Contributions/Vagrant`. What will I do ?

Something like `Contributions/Provisioning`, `Contributions/Provision`, `Contributions/System` looks more appropriate to me...

**Comment by Pierozi** [comment]
@jubianchi in this case you make new repo `Contributions/Docker` no ?
that should be a mess if we mix all provisioning system in same repo no ?

**Comment by jubianchi** [comment]
@Pierozi 
A typical docker (source) repository will only contain a few files (less than 10 files). 
A typical packer (source) repository will contain a few files (less than 10 files).
A typical vagrant (source) repository will contain a few files (less than 10 files).

Moreover, there are godd chances for those 3 repository to share a lot of scripts, cookbooks, recipes, <whatever> so spreading them among many repositories won't help IMHO.

Moreover (bis) imagine if we want to support Chef, Ansible, Puppet, Docker, Vagrant, Packer, QEMU, <whatever> (again) the number of repositories will grow and then, it will be a mess.

**Comment by Pierozi** [comment]
@jubianchi you got a point :+1: 
in this case we need a great organisation of directories inside this repository.

**Comment by Pierozi** [comment]
@jubianch @Hywan Something like this ?

```
└── Contribution
    ├── Env
    │   ├── Docker
    │   ├── QEMU
    │   └── Vagrant
    ├── Provision
    │   ├── Chef
    │   └── Puppet
    └── System
        └── Packer
```

**Comment by Hywan** [comment]
I like it. However, I don't think `Env`, `Provision` and `System` are not well-named.
`Provisioning` seems better than `Provision` I guess (don't know why, we have to be sure about the vocabulary, with strong references). Why `Packer` is in `System`? What does it mean? Why `Vagrant` is in `Env`? Again, what does it mean?

:-)… you know, just naming.

**Comment by jubianchi** [comment]
@Hywan I think @Pierozi built the tree with that in mind:

* `Env`s  are target systems/softwares
* `Provision` are where provisioning recipes are stored
* `System` is the foundation, packer builds the base images/OSes/VMs

Packer in itself is not really a target: it's a builder which will produce artifacts to be used by `Env`s .
Docker could also be put in `Env` and `System`: for example, in `System` we could put a `Dockerfile` to build the base image (containing php in a given version) and in `Env` we could put the `Dockerfile` to build the Hoa image.

Perhaps another tree could be:

```
└── Contribution/Provisioning
    ├── Targets
    │   ├── Docker
    │   ├── QEMU
    │   └── Vagrant
    ├── Recipes
    │   ├── Ansible
    │   ├── Chef
    │   └── Puppet
    └── Base
        ├── Docker
        └── Packer
```

**Comment by Hywan** [comment]
I like this new one :+1:. I look at @Pierozi to confirm. The vocabulary must not be hardly define because we are in the `Provisioning` repository. In my previous comment, I was suggesting to not rename a repository, in this case it's different because we would only rename directories inside the repository, so it's fine.

**Comment by Pierozi** [comment]
@jubianchi great like this, you had known how to explain my mind :)
Targets are good naming, because we can also create file for different cloud provider, like Google, Amazon, Digitalocean... and this is definitely a final target.

**Comment by Hywan** [comment]
I will try to find time today to create this repository.

**Comment by Hywan** [comment]
Seems like I forgot to do this…

**Comment by Hywan** [comment]
https://github.com/hoaproject/Contributions-Provisioning

**Comment by Hywan** [comment]
@Pierozi, @jubianchi: Please, now create issue on https://github.com/hoaproject/Contributions-Provisioning. As usual, this is a mirror. Merge on http://git.hoa-project.net/Contributions/Provisioning.git/ and @Bhoat will sync everything. @jubianchi already knows the procedure, @Pierozi feel free to ask on IRC.

**Comment by Hywan** [comment]
@Pierozi, @jubianchi You are in charge of this contribution also. You have in the team with admin permissions https://github.com/orgs/hoaproject/teams/contributions-provisioning. Feel free to discuss about this on IRC (`#hoaproject`).
