### ISSUE TITLE
[meta] Add .gitignore file in all repositories to enhance composer user usability

### ISSUE THREAD

**Issue by shulard** [hoaproject/Central#22]
Hello,

We discussed here hoaproject/Devtools#16 about adding `.gitignore` files to repos. This file will help Composer users which also want to contribute to do not commit unnecessary files (vendor, .lock).

This issue is here to discussed what need to be ignored before create all these files.

For me, the simplest can be :

```
/vendor/
composer.lock
```

The `composer.lock` is ignore here to be coherent with the Rüsh Release process used by Hoa.

------

Progression:
* [x] Acl
* [x] Bench
* [x] Cache
* [x] Compiler
* [x] Console
* [x] Core
* [x] Database
* [x] Devtools
* [x] Dispatcher
* [x] Dns
* [x] Eventsource
* [x] Fastcgi
* [x] File
* [x] Filter
* [x] Graph
* [x] Http
* [x] Iterator
* [x] Json
* [x] Locale
* [x] Log
* [x] Mail
* [x] Math
* [x] Memory
* [x] Mime
* [x] Model
* [x] Notification
* [x] Praspel
* [x] Promise
* [x] Prototype
* [x] Realdom
* [x] Regex
* [x] Registry
* [x] Router
* [x] Ruler
* [x] Serialize
* [x] Session
* [x] Socket
* [x] Stream
* [x] Stringbuffer
* [x] Translate
* [x] Tree
* [x] Ustring
* [x] View
* [x] Visitor
* [x] Websocket
* [x] Worker
* [x] Xml
* [x] Xmlrpc
* [x] Xyl
* [x] Zombie

**Comment by Hywan** [comment]
Hello :-),

First, there is no link between Rush Release and Composer.
Then, maybe: `vendor/` instead of `/vendor/` would be better. What about `vendor/*`, what's the difference between them?

Also, should we add IDE/editors files, such as:
  * `*.swp` for Vim,
  * `#…` for Emacs,
  * etc.

Do we assume users will use Vim, Emacs, PHPStorm and SublimeText to contribute? If yes, then we can use this gitignore file: https://www.gitignore.io/api/composer,vim,emacs,phpstorm,sublimetext.

Whilst gitignore.io seems to provide an exhaustive `.gitignore` file, what if we would like to add a new editor? We will have to patch all the `.gitignore` file. Is it an issue?

Thoughts? Should we git-ignore only Composer or also IDE and editors @hoaproject/hoackers?

**Comment by patkar** [comment]
Only ignore project specific stuff, such composer. Never clutter .gitignore with IDE stuff. For IDE files users MUST HAVE a gitignore global file. https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by Hywan** [comment]
@patkar Agree with this.

**Comment by jubianchi** [comment]
@patkar +1

@Hywan 

* vendor/ and vendor/* will produce the same result
* /vendor/ might be better as it will cause git to only ignore the vendor directory in the root of the repository. vendor/ will ignore it everywhere in the repo.

**Comment by Hywan** [comment]
@jubianchi Thanks.
@shulard So… let's go with your proposal. Seems good for :+1:!

**Comment by Hywan** [comment]
@shulard What we used to do in this case is: Creating one issue per repository, with a link to this one. In this case, this issue will be a meta issue and will help to track the work. Then, you will have to create one PR per repository with a “Fix #xxx” in its description, where “xxx” is the ID of the issue (not the meta issue). We will close this meta issue manually when everything will be done.

**Comment by Hywan** [comment]
@shulard Oh, and before creating PR for all repositories, let's try with one. Then we will review it, and after that, it will be the same work for all libraries :smiley:.

**Comment by shulard** [comment]
Hello,

Ok, I'll create the first PR. Maybe we should list all the repos that must be updated with that file.

**Comment by Hywan** [comment]
@shulard Every library listed here: http://hoa-project.net/.

**Comment by shulard** [comment]
Oki :smile:

**Comment by Hywan** [comment]
I just updated the description of this issue to include the progression.

**Comment by Hywan** [comment]
@shulard Check the checkboxes only when merged.

**Comment by shulard** [comment]
All the PRs have been created :sweat_smile:

**Comment by Hywan** [comment]
Good work :+1:!
I will try to merge everything after the lunch :smile:!

**Comment by Hywan** [comment]
Excellent work. Everything has been merged. Thank you very much :+1:!

**Comment by Hywan** [comment]
It just destroys the statistics of the week, haha:

![stats](https://graphs.waffle.io/hoaproject/central/throughput.svg)

**Comment by shulard** [comment]
The same for my contribution graph :smile:
