### ISSUE TITLE
Update all composer.json for the `support` entry

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Central#37]
The `support` entry is set to:
```json
    "support": {
        "email" : "support@lists.hoa-project.net",
        "irc"   : "irc://irc.freenode.org/hoaproject",
        "source": "http://git.hoa-project.net/"
    },
```
This is wrong for the `email` part. We must fix it. Any proposal @hoaproject/hoackers?

**See https://github.com/hoaproject/Central/issues/37#issuecomment-245853247 for the diff and issue templates**.

### Progression

  * [x] `Acl`,
  * [x] `Bench`,
  * [x] `Cache`,
  * [x] `Cli`,
  * [x] `Compiler`,
  * [x] `Consistency`,
  * [x] `Console`,
  * [x] `Core`,
  * [x] `Database`,
  * [x] `Devtools`,
  * [x] `Dispatcher`,
  * [x] `Dns`,
  * [x] `Event`,
  * [x] `Eventsource`,
  * [x] `Exception`,
  * [x] `Fastcgi`,
  * [x] `File`,
  * [x] `Graph`,
  * [x] `Http`,
  * [x] `Irc`,
  * [x] `Iterator`,
  * [x] `Json`,
  * [x] `Locale`,
  * [x] `Log`,
  * [x] `Mail`,
  * [x] `Math`,
  * [x] `Memory`,
  * [x] `Mime`,
  * [x] `Model`,
  * [x] `Notification`,
  * [x] `Praspel`,
  * [x] `Promise`,
  * [x] `Protocol`,
  * [x] `Prototype`,
  * [x] `Realdom`,
  * [x] `Regex`,
  * [x] `Registry`,
  * [x] `Router`,
  * [x] `Ruler`,
  * [x] `Serialize`,
  * [x] `Session`,
  * [x] `Socket`,
  * [x] `Stream`,
  * [x] `String`,
  * [x] `Stringbuffer`,
  * [x] `Test`,
  * [x] `Translate`,
  * [x] `Tree`,
  * [x] `Ustring`,
  * [x] `View`,
  * [x] `Visitor`,
  * [x] `Websocket`,
  * [x] `Worker`,
  * [x] `Xml`,
  * [x] `Xmlrpc`,
  * [x] `Xyl`,
  * [x] `Zformat`,
  * [x] `Zombie`,
  * [x] ` `.

**Comment by osaris** [comment]
Discourse can create new topic from incoming email. We could create a new support@hoa-project.net redirection to discourse. What do you think about this solution ?

**Comment by Pierozi** [comment]
Yes this must be lead by discourse from now it should be the official communication way.

+1 for @osaris topic

**Comment by Hywan** [comment]
@osaris hmm interesting feature. So OK for `support@hoa-project.net`.

**Comment by Hywan** [comment]
I have added the progression section. Feel free to patch all the libraries!

**Comment by Pierozi** [comment]
It is already operational if we send email to support@hoa-project.net ?

**Comment by Hywan** [comment]
Nop. @Pierozi and @osaris, you are administrators of discourse.hoa-project.net. Can you configure this please?

**Comment by Pierozi** [comment]
I've setup category `Support` [it's seems work fine](http://discourse.hoa-project.net/t/setup-topic-through-mail/181) 

The email we must used for create new Topic under Category Support is :
hoa_project+support@discoursemail.com

**Comment by Jir4** [comment]
So now we have to update all `composer.json` ?

**Comment by Pierozi** [comment]
It should be preferable first to check if we can create an alias support@hoa-project.net
guess @Hywan can check-it on gandi

**Comment by Hywan** [comment]
I am creating the alias.

**Comment by Hywan** [comment]
I have written to `support@hoa-project.net` and here the answer I got:
> We're sorry, but your email message to ["support@hoa-project.net"] (titled Testing auto-creation of Discourse topic from support@hoa) didn't work.

> None of the destination email addresses are recognized. Please make sure that you are sending to the correct email address provided by staff.

**Comment by Pierozi** [comment]
you need to keep the `+support` like this `hoa_project+support@discoursemail.com`

**Comment by Hywan** [comment]
![screen shot 2016-09-09 at 09 05 36](https://cloud.githubusercontent.com/assets/946104/18378347/be70df30-766c-11e6-9c7b-1f8e5e75492c.png)

**Comment by Pierozi** [comment]
i've update config in discourse, [it's works now!](http://discourse.hoa-project.net/t/try-a-post-by-forwarding-mail/183)

**Comment by Pierozi** [comment]
We can go with this informations for composer.json

```
"support": {
   "email"    : "support@hoa-project.net",
    "irc"     : "irc://irc.freenode.org/hoaproject",
    "forum"   : "http://users.hoa-project.net",
    "source"  : "https://git.hoa-project.net"
}
```

**Comment by Hywan** [comment]
@Pierozi Is it possible to have `https://users.hoa` (which redirects to `http://…`)? In case we have TLS one day, we won't need to rewrite all the `composer.json` file.

**Comment by Pierozi** [comment]
It's not recommended because browser force cycle redirection...

**Comment by Hywan** [comment]
OK, let's so like that.

**Comment by Hywan** [comment]
I have opened https://github.com/hoaproject/Central/issues/39 and https://github.com/hoaproject/Central/issues/40 to get new API on central.hoa. It will help us to add the `docs` property and a better `source` property.

**Comment by Hywan** [comment]
So here is the patch to “apply” (not verbatim because lines change but the diff body should be identical)

```diff
     "support": {
-        "email" : "support@lists.hoa-project.net",
-        "irc"   : "irc://irc.freenode.org/hoaproject",
-        "source": "http://git.hoa-project.net/"
+        "email" : "support@hoa-project.net",
+        "irc"   : "irc://chat.freenode.net/hoaproject",
+        "forum" : "http://users.hoa-project.net/",
+        "docs"  : "https://central.hoa-project.net/Documentation/Library/Acl",
+        "source": "https://central.hoa-project.net/Resource/Library/Acl"
     },
```

What do we see?
  1. An updated `email` entry: No more mailing-lists, just a basic email, already configured to open a topic on Discourse,
  2. An updated `irc` entry: `freenode.org` redirects to `freenode.net` and the recommended domain is `chat`, not `irc`,
  3. An updated `source` entry (pushed to the end of the list): Using the Central HTTP API to get the correct repository directly instead of the home of all repositories,
  4. A new `forum` entry: Using our `users.hoa-project.net` redirection to Discourse,
  5. A new `docs` entry: Using the new Central HTTP API (see https://github.com/hoaproject/Central/pull/40) to get a direct link to the appropriated hack book chapter.

Thoughts?

**Comment by Grummfy** [comment]
seems good for me

**Comment by Hywan** [comment]
Any help is welcomed here :-).

**Comment by Hywan** [comment]
**Thank you** all for your precious help! Now we have nice `composer.json` files with useful links inside: IRC channel, mails to get help (with auto-post to our forum), forum, documentation and source!

👏 👏 👏 !
