### ISSUE TITLE
add tag on composer?

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Central#45]

**Comment by Hywan** [comment]
Can you elaborate please?

**Comment by Hywan** [comment]
Please, can you elaborate?

**Comment by Grummfy** [comment]
Yes,
you should add tag here, on this repository to be available through composer and having the possibility to select a specific version

**Comment by Hywan** [comment]
What is it? I don't get it.

**Comment by Hywan** [comment]
@Grummfy Should we close this issue?

**Comment by Grummfy** [comment]
yes, because I forget why ;)
