### ISSUE TITLE
Happy new year!

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Central#48]
### Progression 
- [x] `Acl`,
- [x] `Bench`,
- [x] `Cache`,
- [x] `Cli`,
- [x] `Compiler`,
- [x] `Consistency`,
- [x] `Console`,
- [x] `Core`,
- [x] `Database`,
- [x] `Devtools`,
- [x] `Dispatcher`,
- [x] `Dns`,
- [x] `Event`,
- [x] `Eventsource`,
- [x] `Exception`,
- [x] `Fastcgi`,
- [x] `File`,
- [x] `Graph`,
- [x] `Http`,
- [x] `Irc`,
- [x] `Iterator`,
- [x] `Json`,
- [x] `Locale`,
- [x] `Log`,
- [x] `Mail`,
- [x] `Math`,
- [x] `Memory`,
- [x] `Mime`,
- [x] `Model`,
- [x] `Notification`,
- [x] `Praspel`,
- [x] `Promise`,
- [x] `Protocol`,
- [x] `Prototype`,
- [x] `Realdom`,
- [x] `Regex`,
- [x] `Registry`,
- [x] `Router`,
- [x] `Ruler`,
- [x] `Serialize`,
- [x] `Session`,
- [x] `Socket`,
- [x] `Stream`,
- [x] `String`,
- [x] `Stringbuffer`,
- [x] `Test`,
- [x] `Translate`,
- [x] `Tree`,
- [x] `Ustring`,
- [x] `View`,
- [x] `Visitor`,
- [x] `Websocket`,
- [x] `Worker`,
- [x] `Xml`,
- [x] `Xmlrpc`,
- [x] `Xyl`,
- [x] `Zformat`,
- [x] `Zombie`,
- [x] ` `.

### Progression reviewed and merged
- [x] `Acl`,
- [x] `Bench`,
- [x] `Cache`,
- [x] `Cli`,
- [x] `Compiler`,
- [x] `Consistency`,
- [x] `Console`,
- [x] `Core`,
- [x] `Database`,
- [x] `Devtools`,
- [x] `Dispatcher`,
- [x] `Dns`,
- [x] `Event`,
- [x] `Eventsource`,
- [x] `Exception`,
- [x] `Fastcgi`,
- [x] `File`,
- [x] `Graph`,
- [x] `Http`,
- [x] `Irc`,
- [x] `Iterator`,
- [x] `Json`,
- [x] `Locale`,
- [x] `Log`,
- [x] `Mail`,
- [x] `Math`,
- [x] `Memory`,
- [x] `Mime`,
- [x] `Model`,
- [x] `Notification`,
- [x] `Praspel`,
- [x] `Promise`,
- [x] `Protocol`,
- [x] `Prototype`,
- [x] `Realdom`,
- [x] `Regex`,
- [x] `Registry`,
- [x] `Router`,
- [x] `Ruler`,
- [x] `Serialize`,
- [x] `Session`,
- [x] `Socket`,
- [x] `Stream`,
- [x] `String`,
- [x] `Stringbuffer`,
- [x] `Test`,
- [x] `Translate`,
- [x] `Tree`,
- [x] `Ustring`,
- [x] `View`,
- [x] `Visitor`,
- [x] `Websocket`,
- [x] `Worker`,
- [x] `Xml`,
- [x] `Xmlrpc`,
- [x] `Xyl`,
- [x] `Zformat`,
- [x] `Zombie`,
- [x] ` `.

**Comment by Hywan** [comment]
@vonglasow Only `Hoa\Realdom` remains. Do you have time for this one please?

**Comment by vonglasow** [comment]
@Hywan yes I have but after verification on commit https://github.com/hoaproject/Realdom/commit/e2797c6739811631343d43902987fec2c8b5ef0e I can see this merged so I don't know what I need to do more.

**Comment by Hywan** [comment]
@vonglasow Sorry, confusion…
