### ISSUE TITLE
Online API browser

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Central#53]
Hello fellow @hoaproject/hoackers and users!

I would like to have a nice online API browser for our libraries. Ready?

# Intro

So far, we have tried http://api.hoa-project.net/, which is the result of [Doxygen](http://www.stack.nl/~dimitri/doxygen/) output.

Is it a solution we could maintain? Do we have better alternatives? What do you expect from an API browser?

# Solutions for PHP

  * [Doxygen](http://www.stack.nl/~dimitri/doxygen/),
  * [Sami](https://github.com/FriendsOfPHP/sami),
  * [ApiGen](http://www.apigen.org/),
  * [PHPDox](http://phpdox.de/),
  * [phpDocumentor](https://www.phpdoc.org/).

Personally, I don't like any of them.

# Solutions in other languages

  * In Rust with [`rustdoc`](https://github.com/rust-lang/rust/tree/master/src/doc), [example](https://doc.rust-lang.org/std/), [source code](https://github.com/rust-lang/rust/tree/b1363a73ede57ae595f3a1be2bb75d308ba4f7f6/src/librustdoc),
  * In Elm, [example](http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html-Attributes),
  * In Haskell, [hoogle](https://www.haskell.org/hoogle/), maybe not relevant for us since it is strongly-base on types,
  * In Caml, [example](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Array.html), haha, kidding…

# Build our own?

I really like the approach of `rustdoc`, the style, the fact that the code must be extremely documented, and the API is not the first-citizen. Look at [Tagua VM](http://tagua.io), the https://tagua-vm.github.io/parser/ page represents the documentation of the `tagua-parser` library. 

For each class, we have a long description. Then we have modules (namepaces in PHP) with a description.

For each function (for instance [`parse`](https://tagua-vm.github.io/parser/tagua_parser/fn.parse.html)), we have a description, and an example. The API is even not documented. Well, this discussion is part of the RFC #58.

But the browsing experience is great.

# Outro

All API documentation generator I tried in PHP didn't catch me. In other languages, like Rust or Elm, we have very nice ideas. We must get inspired from them.

I am not afraid of building a new tool. I personally thing this is the direction to take.

Thoughts?

**Comment by vonglasow** [comment]
Have you tried [apidoc](http://apidocjs.com/) ?

**Comment by 1e1** [comment]
Quick and dirty answer:
How can it be filled by Praspel and typed functions (new in PHP7)?
Can we use Atoum for extracting some examples? 
I will enjoy if the generator need no more comments.

**Comment by 1e1** [comment]
Remember the code is the best documentation!
Notice: in an online API browser we are mainly looking for public methods.

**Comment by Hywan** [comment]
@vonglasow APIDoc is for Rest API, no?
@1e1 We need to expose all methods, whatever the visibility they have, you don't know who is using your libray and for what. For the rest, I didn't understand what you meant, sorry :-/.

**Comment by 1e1** [comment]
This API browser would not add extra comments for generating the documentation. 
There is enough constraints from other tools. It should use these constraints as inputs.

**Comment by Pierozi** [comment]
As RFC #52 will produce high quality and dynamic content
We should be able to extract Markdown from code and generate HTML verison.

Maybe http://www.mkdocs.org could be usefull ?

**Comment by Hywan** [comment]
MKDocs looks nice, but I am afraid this is too much oriented for documentation, and not **API** documentation, aka code-oriented. What do you think? Do you think it will be difficult to bend MKDocs for an API browser?

**Comment by Hywan** [comment]
Current implementation https://github.com/Hywan/Kitab.

**Comment by harikt** [comment]
It looks like you love parsing the docblocks. I have came across lithium which does something similar. Not a standalone one. But it has some plugin when installed your whole framework docs all will be shown.

The plugin is :  https://github.com/UnionOfRAD/li3_docs

The documentation written in class is as 

https://github.com/UnionOfRAD/lithium/blob/5d9a06b8667e20490ef5ccb3275be8824f77666b/action/Controller.php#L15 

once it is rendered you will see something as : http://li3.me/docs/api/lithium/1.1.x/lithium/action/Controller . 

I guess this is what you are looking for. I looked at Kitab, but as it has less information how the docs should be written etc I am not very sure also.

**Comment by Hywan** [comment]
@harikt The format is defined in RFC #58. The output is not exactly what we want. We are looking for something closer to what `rustdoc` does.

**Comment by Hywan** [comment]
# Yesterday progressions

## A namespace page

![kitab_1](https://cloud.githubusercontent.com/assets/946104/24036329/592cc806-0af9-11e7-81c8-9507c8a88ea5.png)

On the left, we have the navigation, which is “all the sibling data”. You must understand it as “namespaces in the same level”.

On the center, we see one namespace in details, with all entities it contains: Classes, interfaces, traits, and functions.

## A class page

![kitab_2](https://cloud.githubusercontent.com/assets/946104/24036330/592cf06a-0af9-11e7-87a6-3f811838464a.png)

# Today progression

The class page has been enhanced with more data. Markdown is converted into HTML for the doc comment attached to methods. We have syntax highlighting. Markdown to HTML does not auto-convert entity names (like class names) into links yet. This is expected in a close future.

![screen shot 2017-03-17 at 10 02 55-fullpage](https://cloud.githubusercontent.com/assets/946104/24036405/b13865b4-0af9-11e7-9412-ecd57cb9129e.png)

The class documentation will be placed just before the “Methods” heading.

**Comment by Hywan** [comment]
# Today progression

And now we have a static search engine
![screen shot 2017-03-21 at 11 12 47](https://cloud.githubusercontent.com/assets/946104/24142742/cc6bbd0a-0e27-11e7-9c63-beec151ad591.png)

It is kind of slow when we have more than 600 files to analyse, but I am working on a cache (the slow part is to build the search index, we can cache it, but I don't know how to orchestrate that).

Anyway, it works great 🙂. I have decided to write it with Elm, because why not.

**Comment by Hywan** [comment]
Great news! The search data are now compiled ahead-of-time. What does it mean? 3 files are now computed:

  1. `search-database.json`, contains all the search information (never used by the client-side, never loaded, only needed for the compilation step, moved to the frontend just for debugging),
  2. `search-index.js`, contains the serialized and compressed index, it is compiled ahead-of-time by Kitab, the client only unserializes it and here we go,
  3. `search-metadata.js`, contains metadata useful to print results to the user, like URL, real symbol name, and description.

Having the index and the metadata separated really helps to reduce the size of the index (by a factor of 65% with my recent tests).

Why doing this? To reduce the initialisation of the search on the client-side. Now, initialisation of the search drops from 17s to… 369ms :tada: with a index representing 606 files. Here are more numbers:

Description | Kitab only | Kitab and its dependencies
-|------------ | -------------
Number of PHP files to analyse | 29 | 606
Time to compile everything | 0.25s | 6.57s
Size of `search-database.json` | 5.4Kb | 149Kb
Size of `search-index.js` | 4.4Kb | 199Kb
Size of `search-metadata.js` | 3.9Kb | 117Kb
Time to initialize the search on client-side | ? | 369ms

I am very happy with these results. Not to say that `search-index.js` and `search-metadata.js` are easily cachable with a 3xx HTTP code. They are purely static.

The size of the search module `search.elm.js` is 92Kb. So for Kitab only, the client loads 100.3Kb, and for Kitab and its dependencies, the client loads 408Kb, **once**.

We have a complete reactive UI with an advanced search for 600+ files for 400Kb. This is still less than Ember or Angular alone —just the framework, not the app— ([source](https://gist.github.com/Restuta/cda69e50a853aa64912d)).

**Comment by Hywan** [comment]
Interface support for the HTML target are better.
Class and interface constants are supported by both the IR and the HTML target (including constant visibility, and default values, for inline or grouped form, resp. `const A; const B;` or `const A, B;`).

![screen shot 2017-04-26 at 15 29 47](https://cloud.githubusercontent.com/assets/946104/25436967/3553cc0c-2a95-11e7-9a62-af3c0bde222b.png)

**Comment by Grummfy** [comment]
Seems really nice. Just a nice feature, for future usage outside Hoa could be a way to +/- compile it to other template style/design

**Comment by Hywan** [comment]
@Grummfy Sure. This is always the case. Choose another target, and here you go.

**Comment by Hywan** [comment]
Progression summary:

1. Attributes are supported (https://github.com/Hywan/Kitab/commit/9f376273df5854fe873da410011770cf54fae0eb),
2. Introduce namespace description, see below please (https://github.com/Hywan/Kitab/commit/9474b3499ef76714f6ddfbfc789d3c8cfe52a8ee and https://github.com/Hywan/Kitab/commit/c6b8f3e53bd36ebfd83251ad5d4a8b3f897f9189),
3. Better global/unnamespaced entities support (https://github.com/Hywan/Kitab/commit/b61fce887931c2434378f345683c70fed25a512f),
4. Functions are supported (https://github.com/Hywan/Kitab/commit/1c753b10ea5834d0565d40c073c7897ff5f201b8),
5. Links to source have been added, please see below (https://github.com/Hywan/Kitab/commit/7fa57a11d6f6e773f31544f11af3fdbdc502541b and some others).

Note about namespace description. Any classes, interfaces, traits, or functions can have a block comment attached to it, in a single place. However, for namespaces, we have many locations where to write the documentation. Because this is not obvious and undeterministic, I have decided to look for a `README.md` file in the directory representing the namespace —with regards to the PSR-4 standard. If such a file exists, then we use it as the namespace description. Thus, I have introduced a new `--with-composer` option to read the PSR-4 mappings from a `composer.json` file. Thoughts? My first idea was to add a new special `Description.md`, but using `README.md` makes a lot of sense: It describes the content of the current directory, and it is displayed as HTML on Github, and Gitlab, which is very useful too.

About links to source, it is attached to each entities (classes, interfaces, traits, functions, and even methods).

**Here is an online example** https://hywan.github.io/Kitab/kitab/index.html of https://github.com/Hywan/Kitab. On this documentation homepage, you can see the `README.md` of the `src/` directory. Below that, you have the Classes and Namespaces Sections. I have found a bug just right now, so links to namespaces are broken, but here is the link to the `Kitab\Compiler` namespace, https://hywan.github.io/Kitab/kitab/compiler/index.html, and here is the documentation for the `Kitab\Compiler\Compiler` class, https://hywan.github.io/Kitab/kitab/compiler/Compiler.html. You can see the Attributes, and Methods Section. All the `[src]` links are working. For example, links to the `compile` method, https://hywan.github.io/Kitab/kitab/compiler/Compiler.source.html#L.91-106. The static search engine is also working.

Please, fill bugs or discuss here :-). Feedbacks are really appreciated!

**Comment by Grummfy** [comment]
can you add an example where you use php 7 synthaxe with return, scalar type, etc.

Otyherwise nothing special to say it seems really nice

**Comment by Hywan** [comment]
@Grummfy Like this one https://hywan.github.io/Kitab/kitab/compiler/intermediaterepresentation/Into.html?

**Comment by Grummfy** [comment]
Well in this case, I would expect that "Type" or "File" would be clickable because thier are class that exist inside the documentation. For that's the only expected things that I see.

As extra information/plugins, I really enjoy to have stuff like [phpxref](http://phpxref.sourceforge.net/)  to cross check the usage. But not directly accessible.

**Comment by Hywan** [comment]
> As extra information/plugins, I really enjoy to have stuff like phpxref to cross check the usage. But not directly accessible.

Can you give an example please?

**Comment by Grummfy** [comment]
http://phpxref.sourceforge.net/phpxref-xaraya/nav.html.gz?index.html.gz

**Comment by Hywan** [comment]
This a tree explorer, yes, and… ? I don't understand what you are asking :-).

**Comment by Hywan** [comment]
Bug in namespace links is now fixed, https://hywan.github.io/Kitab/kitab/index.html.

Next steps:

* Being able to configure the logo,
* Add a `index.html` file at the root of the project to redirect to a particular namespace index (becase https://hywan.github.io/Kitab/ does not link to anything, we have to choose  the `kitab` directory),
* Make more code “clickable”, like class-like types in parameters.

After that, we will be good to try a 1.0 beta, and deploy it on Hoa.

**Comment by Hywan** [comment]
![screen shot 2017-05-30 at 12 39 04](https://cloud.githubusercontent.com/assets/946104/26579663/ffa7dab6-4534-11e7-9871-c2d63ffb5d64.png)

And here we go, since https://github.com/Hywan/Kitab/commit/1950f62048dd98c82242dffb03fd32fce8993c08, all qualified names are clickable. I still have an issue with `extends` that are not linkable, a small conflict with Prism (`c-like` profile).

**Comment by Hywan** [comment]
# Progression summary

* I am writing the documentation of Kitab itself,
* New IR: `Documentation`, to represent the whole documentation, or get the description (first line),
* Add entity descriptions on the namespace index (e.g. https://hywan.github.io/Kitab/kitab/compiler/intermediaterepresentation/index.html, the Classes Section lists all classse with the description inlined), since https://github.com/Hywan/Kitab/commit/68116025ac1c2b59b544c85ecfbf8a4074874bf7,
* Support `static` attribute in the IR, since https://github.com/Hywan/Kitab/commit/b3ef5a10f16cef9f82eeb07f149fdb33f3e1d5c9,
* Support variadic parameter,
* Kitab works as a dependency or if installed globally, since https://github.com/Hywan/Kitab/commit/0c0526707efd2abd3eb022a77a1dfd2f3ada54aa (thanks @jubianchi!),
* The HTML target is responsive, since https://github.com/Hywan/Kitab/commit/ae04cce3a5d3d89dbacec5fc328f7bdcfbecf509.

I find interesting how to document things without saying: “Return bla bla” or “Get bla bla”, because the name of the function or method **must be** self-explanatory! So taking the example of `inNamespace` in https://hywan.github.io/Kitab/kitab/compiler/intermediaterepresentation/Entity.html, I used the following description:

> An entity is in a namespace if its fully-qualified name contains at least one namespace separator (aka `\`).

Actually, this is the only explanation we expect at this step. We know the method is called `inNamespace` so saying something like: “Check if the name is in a namespace” is totally stupid.

This is interesting to rethink how we write documentation.

**Comment by Pierozi** [comment]
Really nice, I like the Namespace page related to Readme, a good one :+1:

**Comment by Hywan** [comment]
It renders on Github too! On Github: https://github.com/Hywan/Kitab/tree/master/src/Compiler, on Kitab: https://hywan.github.io/Kitab/kitab/compiler/index.html.

**Comment by Hywan** [comment]
And now, Kitab can test your examples with `./bin/kitab test`. More at https://github.com/Hywan/Kitab/pull/3.

**Comment by Hywan** [comment]
What's next?

- [ ] Documenting everything inside Kitab.
- [ ] Try to use Kitab with a non-PSR-4 project.
- [ ] Move Kitab into the Hoa organisation.
- [ ] Release the 1.0 version.

**Comment by brzuchal** [comment]
None of the links to generated documentation doesn't work. Could you provide working one?

**Comment by Hywan** [comment]
Yes, we are migrating the repository into the Hoa organisation since this morning. Give me some hours to fix everything :-).

**Comment by Hywan** [comment]
@brzuchal https://hywan.github.io/Kitab/kitab/index.html :-)

**Comment by Hywan** [comment]
The 0.10 version has been tagged https://github.com/hoaproject/Kitab/releases. The version is stable. We use it at work.

It is implemented inside `hoa/test`. We will start to deploy the documentation on the hoa-project.net site soon.
