### ISSUE TITLE
Provide Supported PHP-Versions in all composer.json files

### ISSUE THREAD

**Issue by Idrinth** [hoaproject/Central#70]
Currently people wanting to use your libraries are forced to look up a secondary library (hoa/consistency) to figure out the officially supported version.
Adding the required php-version to the other libraries would provide an easier and quicker way to figure out if the given version is useable as intended.

This has pretty much the same reasoning as #33, since quite often the developers do not have complete control over the provided enviroment and this would speed up checking the requirements.

**Comment by Grummfy** [comment]
Hello,
thanks or reaching us. That's an excellent idea and it's quiet simple to do.

**Comment by vonglasow** [comment]
Hello,

thanks it looks good idea, you can follow here the progression of this work.

# Progression

  * [ ] `Acl`,
  * [ ] `Compiler`,
  * [ ] `Consistency`,
  * [ ] `Console`,
  * [ ] `Database`,
  * [ ] `Dispatcher`,
  * [ ] `Event`,
  * [ ] `Exception`,
  * [ ] `Graph`,
  * [ ] `Iterator`,
  * [ ] `Json`,
  * [ ] `Locale`,
  * [ ] `Mail`,
  * [ ] `Math`,
  * [ ] `Mime`,
  * [ ] `Protocol`,
  * [ ] `Registry`,
  * [ ] `Ruler`,
  * [ ] `Socket`,
  * [ ] `Stream`,
  * [ ] `Ustring`,
  * [ ] `View`,
  * [ ] `Visitor`,
  * [ ] `Websocket`,
  * [ ] `Zombie`.

**Comment by vonglasow** [comment]
All composer.json files is up to date.

**Comment by Hywan** [comment]
Releases will come granually.

**Comment by Idrinth** [comment]
thank you
