### ISSUE TITLE
Drop Hoa\Log

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Central#76]
Hello @hoaproject/hoackers,

I would like to drop the `hoa/log` library because:

* It is not complete,
* It does not respect any PSR,
* There is tons of great logs library out there,
* This library does not bring anything relevant compared to the other ones.

As usual, the library will be marked as deprecated, the repository will be kept.

Thoughts?

**Comment by vonglasow** [comment]
Looks not a problem for me. Just one thing, which one should we/you recommend as you said `there is a tons of great logs library`.

**Comment by Hywan** [comment]
https://packagist.org/?q=log&p=0 :-]

monolog for instance

**Comment by Grummfy** [comment]
* monolo/monolog or apache/log4php seems to be good suggestion
* don't forget to update the readme and packgist about it.

**Comment by Pierozi** [comment]
Good to me :+1:

**Comment by osaris** [comment]
That make sense !

**Comment by Hywan** [comment]
Done in https://github.com/hoaproject/Central/issues/90.
