### ISSUE TITLE
Configure mirror on Gitlab

### ISSUE THREAD

**Issue by vonglasow** [hoaproject/Central#77]
# Create a mirror on gitlab

Add description and logo

## Progressions
- [x] [Contributions-Atom-Pp](https://git.hoa-project.net/Contributions/Atom/Pp.git) PP —the grammar description language from Hoa\Compiler— support in Atom.
- [x] [Contributions-Atoum-PraspelExtension](https://git.hoa-project.net/Contributions/Atoum/PraspelExtension.git) Include Praspel inside atoum.
- [x] [Contributions-Emacs-Pp](https://git.hoa-project.net/Contributions/Emacs/Pp.git) PP —the grammar description language from Hoa\Compiler— support in Emacs.
- [x] [Contributions-Provisioning](https://git.hoa-project.net/Contributions/Provisioning.git) Provisioning scripts related to Hoa.
- [x] [Contributions-Symfony-BenchBundle](https://git.hoa-project.net/Contributions/Symfony/BenchBundle.git) The Hoa\Bench Symfony2 bundle.
- [x] [Contributions-Symfony-ConsoleBridge](https://git.hoa-project.net/Contributions/Symfony/ConsoleBridge.git) Hoa\Console to Symfony bundle bridge.
- [x] [Contributions-Symfony-ConsoleBundle](https://git.hoa-project.net/Contributions/Symfony/ConsoleBundle.git) The Hoa\Console Symfony2 bundle.
- [x] [Contributions-Symfony-RulerBundle](https://git.hoa-project.net/Contributions/Symfony/RulerBundle.git) The Hoa\Ruler Symfony2 bundle.
- [x] [Contributions-Vim-Pp](https://git.hoa-project.net/Contributions/Vim/Pp.git) PP —the grammar description language from Hoa\Compiler— support in Vim.
- [x] [Contributions-Zsh-Hoa](https://git.hoa-project.net/Contributions/Zsh/Hoa.git) Hoa\Cli support (autocompletion & co.) in Zsh.

- [x] [Acl](https://git.hoa-project.net/Library/Acl.git) The Hoa\Acl library.
- [x] [Bench](https://git.hoa-project.net/Library/Bench.git) The Hoa\Bench library.
- [x] [Cache](https://git.hoa-project.net/Library/Cache.git) The Hoa\Cache library.
- [x] [Cli](https://git.hoa-project.net/Library/Cli.git) The Hoa\Cli library.
- [x] [Compiler](https://git.hoa-project.net/Library/Compiler.git) The Hoa\Compiler library.
- [x] [Consistency](https://git.hoa-project.net/Library/Consistency.git) The Hoa\Consistency library.
- [x] [Console](https://git.hoa-project.net/Library/Console.git) The Hoa\Console library.
- [x] [Core](https://git.hoa-project.net/Library/Core.git) The Hoa\Core library.
- [x] [Database](https://git.hoa-project.net/Library/Database.git) The Hoa\Database library.
- [x] [Devtools](https://git.hoa-project.net/Library/Devtools.git) The Hoa\Devtools library.
- [x] [Dispatcher](https://git.hoa-project.net/Library/Dispatcher.git) The Hoa\Dispatcher library.
- [x] [Dns](https://git.hoa-project.net/Library/Dns.git) The Hoa\Dns library.
- [x] [Event](https://git.hoa-project.net/Library/Event.git) The Hoa\Event library.
- [x] [Eventsource](https://git.hoa-project.net/Library/Eventsource.git) The Hoa\Eventsource library.
- [x] [Exception](https://git.hoa-project.net/Library/Exception.git) The Hoa\Exception library.
- [x] [Fastcgi](https://git.hoa-project.net/Library/Fastcgi.git) The Hoa\Fastcgi library.
- [x] [File](https://git.hoa-project.net/Library/File.git) The Hoa\File library.
- [x] [Graph](https://git.hoa-project.net/Library/Graph.git) The Hoa\Graph library.
- [x] [Heap](https://git.hoa-project.net/Library/Heap.git) The Hoa\Heap library.
- [x] [Http](https://git.hoa-project.net/Library/Http.git) The Hoa\Http library.
- [x] [Irc](https://git.hoa-project.net/Library/Irc.git) The Hoa\Irc library.
- [x] [Iterator](https://git.hoa-project.net/Library/Iterator.git) The Hoa\Iterator library.
- [x] [Json](https://git.hoa-project.net/Library/Json.git) The Hoa\Json library.
- [x] [Locale](https://git.hoa-project.net/Library/Locale.git) The Hoa\Locale library.
- [x] [Log](https://git.hoa-project.net/Library/Log.git) The Hoa\Log library.
- [x] [Mail](https://git.hoa-project.net/Library/Mail.git) The Hoa\Mail library.
- [x] [Math](https://git.hoa-project.net/Library/Math.git) The Hoa\Math library.
- [x] [Memory](https://git.hoa-project.net/Library/Memory.git) The Hoa\Memory library.
- [x] [Mime](https://git.hoa-project.net/Library/Mime.git) The Hoa\Mime library.
- [x] [Model](https://git.hoa-project.net/Library/Model.git) The Hoa\Model library.
- [x] [Notification](https://git.hoa-project.net/Library/Notification.git) The Hoa\Notification library.
- [x] [Option](https://git.hoa-project.net/Library/Option.git) The Hoa\Option library.
- [x] [Praspel](https://git.hoa-project.net/Library/Praspel.git) The Hoa\Praspel library.
- [x] [Promise](https://git.hoa-project.net/Library/Promise.git) The Hoa\Promise library.
- [x] [Protocol](https://git.hoa-project.net/Library/Protocol.git) The Hoa\Protocol library.
- [x] [Prototype](https://git.hoa-project.net/Library/Prototype.git) The Hoa\Prototype library.
- [x] [Realdom](https://git.hoa-project.net/Library/Realdom.git) The Hoa\Realdom library.
- [x] [Regex](https://git.hoa-project.net/Library/Regex.git) The Hoa\Regex library.
- [x] [Registry](https://git.hoa-project.net/Library/Registry.git) The Hoa\Registry library.
- [x] [Router](https://git.hoa-project.net/Library/Router.git) The Hoa\Router library.
- [x] [Ruler](https://git.hoa-project.net/Library/Ruler.git) The Hoa\Ruler library.
- [x] [Serialize](https://git.hoa-project.net/Library/Serialize.git) The Hoa\Serialize library.
- [x] [Session](https://git.hoa-project.net/Library/Session.git) The Hoa\Session library.
- [x] [Socket](https://git.hoa-project.net/Library/Socket.git) The Hoa\Socket library.
- [x] [Stream](https://git.hoa-project.net/Library/Stream.git) The Hoa\Stream library.
- [x] [String](https://git.hoa-project.net/Library/String.git) The Hoa\String library.
- [x] [Stringbuffer](https://git.hoa-project.net/Library/Stringbuffer.git) The Hoa\Stringbuffer library.
- [x] [Test](https://git.hoa-project.net/Library/Test.git) The Hoa\Test library.
- [x] [Translate](https://git.hoa-project.net/Library/Translate.git) The Hoa\Translate library.
- [x] [Tree](https://git.hoa-project.net/Library/Tree.git) The Hoa\Tree library.
- [x] [Ustring](https://git.hoa-project.net/Library/Ustring.git) The Hoa\Ustring library.
- [x] [View](https://git.hoa-project.net/Library/View.git) The Hoa\View library.
- [x] [Visitor](https://git.hoa-project.net/Library/Visitor.git) The Hoa\Visitor library.
- [x] [Websocket](https://git.hoa-project.net/Library/Websocket.git) The Hoa\Websocket library.
- [x] [Worker](https://git.hoa-project.net/Library/Worker.git) The Hoa\Worker library.
- [x] [Xml](https://git.hoa-project.net/Library/Xml.git) The Hoa\Xml library.
- [x] [Xmlrpc](https://git.hoa-project.net/Library/Xmlrpc.git) The Hoa\Xmlrpc library.
- [x] [Xyl](https://git.hoa-project.net/Library/Xyl.git) The Hoa\Xyl library.
- [x] [Zformat](https://git.hoa-project.net/Library/Zformat.git) The Hoa\Zformat library.
- [x] [Zombie](https://git.hoa-project.net/Library/Zombie.git) The Hoa\Zombie library.

- [x] [Blog](https://git.hoa-project.net/Blog.git/) Blog
- [x] [Central](https://git.hoa-project.net/Central.git/) Central
- [x] [Shop](https://git.hoa-project.net/Shop.git/) Shop

**Comment by Hywan** [comment]
:+1:

**Comment by vonglasow** [comment]
Mirror should be from github, I remove all check box already created to redo with github source repositories

**Comment by shulard** [comment]
Hello, I'll make the mirror URL change to use Github. I add the checkbox list here :

# Specific repos

- [ ] Blog
- [ ] W3
- [ ] Shop
- [ ] Central
- [ ] Infrastructure
- [ ] Keynote
- [ ] Literature
- [ ] Marvirc

## Libraries

- [ ] Contributions-Atom-Pp PP —the grammar description language from Hoa\Compiler— support in Atom.
- [ ] Contributions-Atoum-PraspelExtension Include Praspel inside atoum.
- [ ] Contributions-Emacs-Pp PP —the grammar description language from Hoa\Compiler— support in Emacs.
- [ ] Contributions-Provisioning Provisioning scripts related to Hoa.
- [ ] Contributions-Symfony-BenchBundle The Hoa\Bench Symfony2 bundle.
- [ ] Contributions-Symfony-ConsoleBridge Hoa\Console to Symfony bundle bridge.
- [ ] Contributions-Symfony-ConsoleBundle The Hoa\Console Symfony2 bundle.
- [ ] Contributions-Symfony-RulerBundle The Hoa\Ruler Symfony2 bundle.
- [ ] Contributions-Vim-Pp PP —the grammar description language from Hoa\Compiler— support in Vim.
- [ ] Contributions-Zsh-Hoa Hoa\Cli support (autocompletion & co.) in Zsh.
- [ ] Acl The Hoa\Acl library.
- [ ] Bench The Hoa\Bench library.
- [ ] Cache The Hoa\Cache library.
- [ ] Cli The Hoa\Cli library.
- [ ] Compiler The Hoa\Compiler library.
- [ ] Consistency The Hoa\Consistency library.
- [ ] Console The Hoa\Console library.
- [ ] Core The Hoa\Core library.
- [ ] Database The Hoa\Database library.
- [ ] Devtools The Hoa\Devtools library.
- [ ] Dispatcher The Hoa\Dispatcher library.
- [ ] Dns The Hoa\Dns library.
- [ ] Event The Hoa\Event library.
- [ ] Eventsource The Hoa\Eventsource library.
- [ ] Exception The Hoa\Exception library.
- [ ] Fastcgi The Hoa\Fastcgi library.
- [ ] File The Hoa\File library.
- [ ] Graph The Hoa\Graph library.
- [ ] Heap The Hoa\Heap library.
- [ ] Http The Hoa\Http library.
- [ ] Irc The Hoa\Irc library.
- [ ] Iterator The Hoa\Iterator library.
- [ ] Json The Hoa\Json library.
- [ ] Kitab The Hoa\Kitab library.
- [ ] Locale The Hoa\Locale library.
- [ ] Log The Hoa\Log library.
- [ ] Mail The Hoa\Mail library.
- [ ] Math The Hoa\Math library.
- [ ] Memory The Hoa\Memory library.
- [ ] Mime The Hoa\Mime library.
- [ ] Model The Hoa\Model library.
- [ ] Notification The Hoa\Notification library.
- [ ] Option The Hoa\Option library.
- [ ] Praspel The Hoa\Praspel library.
- [ ] Promise The Hoa\Promise library.
- [ ] Protocol The Hoa\Protocol library.
- [ ] Prototype The Hoa\Prototype library.
- [ ] Realdom The Hoa\Realdom library.
- [ ] Regex The Hoa\Regex library.
- [ ] Registry The Hoa\Registry library.
- [ ] Router The Hoa\Router library.
- [ ] Ruler The Hoa\Ruler library.
- [ ] Serialize The Hoa\Serialize library.
- [ ] Session The Hoa\Session library.
- [ ] Socket The Hoa\Socket library.
- [ ] Stream The Hoa\Stream library.
- [ ] String The Hoa\String library.
- [ ] Stringbuffer The Hoa\Stringbuffer library.
- [ ] Test The Hoa\Test library.
- [ ] Translate The Hoa\Translate library.
- [ ] Tree The Hoa\Tree library.
- [ ] Ustring The Hoa\Ustring library.
- [ ] View The Hoa\View library.
- [ ] Visitor The Hoa\Visitor library.
- [ ] Websocket The Hoa\Websocket library.
- [ ] Worker The Hoa\Worker library.
- [ ] Xml The Hoa\Xml library.
- [ ] Xmlrpc The Hoa\Xmlrpc library.
- [ ] Xyl The Hoa\Xyl library.
- [ ] Zformat The Hoa\Zformat library.
- [ ] Zombie The Hoa\Zombie library.

**Comment by shulard** [comment]
Hello, 

I've checked the repo list on Gitlab, there are some issues to fix :smile:.

## Repo exists but in't mirrored

- [ ] W3
- [ ] Infrastructure
- [ ] Keynote
- [ ] Literature
- [ ] Marvirc

## Repo mirror URL have basic auth details in it.

- [ ] Central
- [ ] Compiler

## Missing repos

- [ ] Tree The Hoa\Tree library.
- [ ] Hoa\Paste

**Comment by vonglasow** [comment]
Thanks for the check so for Tree the repository exist but with wrong url I have checked if I can rename it, currently It's `https://gitlab.com/hoaproject/Tree0` Maybe a typo during the creation or another already existing repository hidden call Tree. Unfortunately, my first try fail I got a 500 error for renaming the repository I need more time to check it.

I have fixed repos with auth details (compiler and Central) for the other I let you configure it.

@shulard You are now master so you should be able to change the rest.

Thanks for your help

**Comment by shulard** [comment]
Maybe `tree` is a reserved keyword in URL... Since the mirror is live, I think it's not the most important here.

I've updated the repos with unactive mirrors and also created static. At the moment it mirror the `git.hoa-project.net` repository but I'll update the URL when the repo will be created on Github.

**Comment by vonglasow** [comment]
Static is operational and tree except for the url is ok I close this ticket as everything is done.

You can reopen it or add a new one if you think it's relevant.

**Comment by Hywan** [comment]
Great work!
