### ISSUE TITLE
no more gitter?

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Central#78]
Hello,
it's seems that gitter/hoa/central is dead.

Is it normal?

It's inside all of our readme, so ?

**Comment by Hywan** [comment]
No it's not. Can you recreate it?

**Comment by Grummfy** [comment]
when I try to create hoaproject/central, I got this error : "You cannot create a channel with a same name that as an already existing repo".

So I create a simple hoaproject room?

**Comment by Hywan** [comment]
Why was it possible before, and not now…?

**Comment by Hywan** [comment]
https://gitter.im/hoaproject already exists.

**Comment by Grummfy** [comment]
it's a private one, not a public one

**Comment by Grummfy** [comment]
hoaproject/central perhaps someone with right on hoaorganisation can recreate it or I create a new one like hoaproject/community ?

**Comment by Grummfy** [comment]
solved by @vonglasow
