### ISSUE TITLE
create repository for atoum-option-extension

### ISSUE THREAD

**Issue by Grummfy** [hoaproject/Central#80]
create a repository for https://github.com/Grummfy/atoum-option-extension inside hoa,
publish it to composer

thanks

**Comment by vonglasow** [comment]
Some changes requested:

- https://github.com/Grummfy/atoum-option-extension/blob/master/.travis.yml Could you add PHP-7.2
- https://github.com/Grummfy/atoum-option-extension/blob/master/composer.json#L2 fix `opton` to option and fix tab indentation (remove tabs)
- https://github.com/Grummfy/atoum-option-extension/blob/master/README.md#documentation Can you remove `The hack book of Hoa\atoum-option-extension contains detailed information about how to use this library and how it works.` as we don't have any hack book for contribution.

Question:
As we don't have hack book as documentation for contribution, it will be interesting to use Kitab as doc generator. What do you think to add some documentation on the code and using Kitab?

**Comment by Grummfy** [comment]
updated

**Comment by vonglasow** [comment]
Fixed since https://github.com/hoaproject/Contributions-Atoum-Option-Extension
