### ISSUE TITLE
Dependency errors when installed with prefer-lowest

### ISSUE THREAD

**Issue by Majkl578** [hoaproject/Central#87]
I am moving the hoaproject/Compiler#83 directly here to Hoa\Central since this apparently seems to be a huge issue across whole Hoa ecosystem where all dependencies are just `~1.0`.

-----

> While attempting to run the suite locally with lowest dependencies (Composer's  `--prefer-lowest`), it crashes right away:
> ```
> $ vendor/bin/hoa test:run -a
> PHP Deprecated:  The (unset) cast is deprecated in /tmp/Compiler/vendor/hoa/consistency/Prelude.php on line 73
> 
> Deprecated: The (unset) cast is deprecated in /tmp/Compiler/vendor/hoa/consistency/Prelude.php on line 73
> 
> Error: The (unset) cast is deprecated in /tmp/Compiler/vendor/hoa/test/.bootstrap.atoum.php at line 7
> $ php -v | head -n 1
> PHP 7.2.3 (cli) (built: Mar 12 2018 20:39:08) ( NTS )
> ```
> 
> When using Compiler as dependency and installing with `--prefer-lowest`, it produces lots of errors, regarding the deprecated cast, but also non-existent class Hoa\Iterator\Buffer. See Travis log here: https://travis-ci.org/schmittjoh/serializer/jobs/371673251#L580
> 
> Compiler must, as a library, require lowest versions of its dependencies in versions it works with.

**Comment by Hywan** [comment]
Let's keep hoa/Compiler#83 opened for now since the discussions happened there :-).
